// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.1";

// src/lib/mcp/tools/list-tickets.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function textResult(data) {
  return { content: [{ type: "text", text: JSON.stringify(data) }] };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/list-tickets.ts
var list_tickets_default = defineTool({
  name: "list_tickets",
  title: "List support tickets",
  description: "List support tickets visible to the signed-in user. Regular users see their own tickets; admins see all tickets.",
  inputSchema: {
    status: z.enum(["open", "in_progress", "resolved", "closed"]).optional().describe("Filter tickets by status."),
    limit: z.number().int().min(1).max(100).optional().describe("Max tickets to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    let query = supabaseForUser(ctx).from("support_tickets").select("id,ticket_number,subject,description,status,priority,category,created_at,updated_at,sla_due_at,resolution_notes").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return { ...textResult(data), structuredContent: { tickets: data ?? [] } };
  }
});

// src/lib/mcp/tools/create-ticket.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z2 } from "npm:zod@^3.25.76";
var create_ticket_default = defineTool2({
  name: "create_ticket",
  title: "Create support ticket",
  description: "Create a new support ticket for the signed-in user.",
  inputSchema: {
    subject: z2.string().trim().min(1).describe("Short summary of the issue."),
    description: z2.string().trim().min(1).describe("Full description of the issue."),
    priority: z2.enum(["P1", "P2", "P3", "P4"]).optional().describe("ITIL priority, P1 highest."),
    category: z2.enum(["incident", "service_request", "change_request", "problem", "question"]).optional().describe("Ticket category.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ subject, description, priority, category }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const { data, error } = await supabaseForUser(ctx).from("support_tickets").insert({
      user_id: ctx.getUserId(),
      subject,
      description,
      ...priority ? { priority } : {},
      ...category ? { category } : {}
    }).select("id,ticket_number,subject,status,priority,category,created_at").single();
    if (error) return errorResult(error.message);
    return { ...textResult(data), structuredContent: { ticket: data } };
  }
});

// src/lib/mcp/tools/get-ticket-comments.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z3 } from "npm:zod@^3.25.76";
var get_ticket_comments_default = defineTool3({
  name: "get_ticket_comments",
  title: "Get ticket comments",
  description: "Read the comment thread on a support ticket. Internal notes are only visible to admins.",
  inputSchema: { ticket_id: z3.string().uuid().describe("The ticket UUID.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ ticket_id }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const { data, error } = await supabaseForUser(ctx).from("ticket_comments").select("id,comment,is_internal,user_id,created_at").eq("ticket_id", ticket_id).order("created_at", { ascending: true });
    if (error) return errorResult(error.message);
    return { ...textResult(data), structuredContent: { comments: data ?? [] } };
  }
});

// src/lib/mcp/tools/add-ticket-comment.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z4 } from "npm:zod@^3.25.76";
var add_ticket_comment_default = defineTool4({
  name: "add_ticket_comment",
  title: "Add ticket comment",
  description: "Add a comment to a support ticket as the signed-in user.",
  inputSchema: {
    ticket_id: z4.string().uuid().describe("The ticket UUID."),
    comment: z4.string().trim().min(1).describe("Comment text.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ ticket_id, comment }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    const { data, error } = await supabaseForUser(ctx).from("ticket_comments").insert({ ticket_id, comment, user_id: ctx.getUserId(), is_internal: false }).select("id,ticket_id,comment,created_at").single();
    if (error) return errorResult(error.message);
    return { ...textResult(data), structuredContent: { comment: data } };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_services_default = defineTool5({
  name: "list_services",
  title: "List purchased services",
  description: "List the services and products purchased by the signed-in user.",
  inputSchema: {
    status: z5.string().optional().describe("Filter by purchase status, e.g. 'active'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    let query = supabaseForUser(ctx).from("user_purchases").select("id,product_id,price_paid,status,purchased_at,next_billing_date,cancelled_at,fulfilled,notes").order("purchased_at", { ascending: false });
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return { ...textResult(data), structuredContent: { services: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-invoices.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.25.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_invoices_default = defineTool6({
  name: "list_invoices",
  title: "List invoices",
  description: "List invoices for the signed-in user, including amounts, status and PDF links.",
  inputSchema: {
    status: z6.string().optional().describe("Filter by invoice status, e.g. 'paid' or 'open'."),
    limit: z6.number().int().min(1).max(100).optional().describe("Max invoices to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    let query = supabaseForUser(ctx).from("invoices").select("id,invoice_number,amount,status,description,due_date,paid_at,pdf_url,created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return { ...textResult(data), structuredContent: { invoices: data ?? [] } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rrsrbmunjsinjuaewnmg";
var mcp_default = defineMcp({
  name: "peritus-one-mcp",
  title: "Peritus ONE",
  version: "0.1.0",
  instructions: "Tools for the Peritus ONE customer portal. Read and create support tickets, read and add ticket comments, and list purchased services and invoices for the signed-in customer. All data is scoped to the authenticated user (admins see all tickets).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_tickets_default,
    create_ticket_default,
    get_ticket_comments_default,
    add_ticket_comment_default,
    list_services_default,
    list_invoices_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
